### ISSUE TITLE
“No member named '...' in 'RPG::SavePicture'”

### ISSUE THREAD

**Issue by bentley** [EasyRPG/Player#1304]
0.5.3 fails to build on OpenBSD 6.2 (which uses clang-5.0.0):

    [1/13] /usr/ports/pobj/easyrpg-0.5.3/bin/c++  -DHAVE_FREETYPE -DHAVE_HARFBUZZ -DHAVE_LIBSNDFILE -DHAVE_LIBSPEEXDSP -DHAVE_MPG123 -DHAVE_OGGVORBIS -DHAVE_OPUS -DHAVE_SDL_MIXER -DHAVE_WINE -DHAVE_XMP -DSUPPORT_AUDIO -DUSE_SDL -DWANT_FMMIDI=2 -I/usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src -I/usr/local/include/liblcf -I/usr/X11R6/include/pixman-1 -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include/freetype2 -I/usr/local/include/harfbuzz -I/usr/local/include/opus -O2 -pipe   -I /usr/X11R6/include -DNDEBUG   -std=gnu++11 -MD -MT CMakeFiles/EasyRPG_Player_Static.dir/src/game_picture.cpp.o -MF CMakeFiles/EasyRPG_Player_Static.dir/src/game_picture.cpp.o.d -o CMakeFiles/EasyRPG_Player_Static.dir/src/game_picture.cpp.o -c /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp
    FAILED: CMakeFiles/EasyRPG_Player_Static.dir/src/game_picture.cpp.o 
    /usr/ports/pobj/easyrpg-0.5.3/bin/c++  -DHAVE_FREETYPE -DHAVE_HARFBUZZ -DHAVE_LIBSNDFILE -DHAVE_LIBSPEEXDSP -DHAVE_MPG123 -DHAVE_OGGVORBIS -DHAVE_OPUS -DHAVE_SDL_MIXER -DHAVE_WINE -DHAVE_XMP -DSUPPORT_AUDIO -DUSE_SDL -DWANT_FMMIDI=2 -I/usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src -I/usr/local/include/liblcf -I/usr/X11R6/include/pixman-1 -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include/freetype2 -I/usr/local/include/harfbuzz -I/usr/local/include/opus -O2 -pipe   -I /usr/X11R6/include -DNDEBUG   -std=gnu++11 -MD -MT CMakeFiles/EasyRPG_Player_Static.dir/src/game_picture.cpp.o -MF CMakeFiles/EasyRPG_Player_Static.dir/src/game_picture.cpp.o.d -o CMakeFiles/EasyRPG_Player_Static.dir/src/game_picture.cpp.o -c /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:56:32: error: no member named 'spritesheet_frame' in 'RPG::SavePicture'
            if (HasSpritesheet() && (data.spritesheet_frame != last_spritesheet_frame || !sheet_bitmap)) {
                                     ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:61:54: error: no member named 'spritesheet_cols' in 'RPG::SavePicture'
                            int frame_width = whole_bitmap->GetWidth() / data.spritesheet_cols;
                                                                         ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:62:56: error: no member named 'spritesheet_rows' in 'RPG::SavePicture'
                            int frame_height = whole_bitmap->GetHeight() / data.spritesheet_rows;
                                                                           ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:67:33: error: no member named 'spritesheet_frame' in 'RPG::SavePicture'
                    last_spritesheet_frame = data.spritesheet_frame;
                                             ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:69:76: error: no member named 'spritesheet_cols' in 'RPG::SavePicture'
                    int sx = sheet_bitmap->GetWidth() * ((last_spritesheet_frame - 1) % data.spritesheet_cols);
                                                                                        ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:70:77: error: no member named 'spritesheet_cols' in 'RPG::SavePicture'
                    int sy = sheet_bitmap->GetHeight() * ((last_spritesheet_frame - 1) / data.spritesheet_cols % data.spritesheet_rows);
                                                                                         ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:70:101: error: no member named 'spritesheet_rows' in 'RPG::SavePicture'
                    int sy = sheet_bitmap->GetHeight() * ((last_spritesheet_frame - 1) / data.spritesheet_cols % data.spritesheet_rows);
                                                                                                                 ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:75:68: error: no member named 'spritesheet_cols' in 'RPG::SavePicture'
                    if (last_spritesheet_frame > 0 && last_spritesheet_frame <= data.spritesheet_cols * data.spritesheet_rows) {
                                                                                ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:75:92: error: no member named 'spritesheet_rows' in 'RPG::SavePicture'
                    if (last_spritesheet_frame > 0 && last_spritesheet_frame <= data.spritesheet_cols * data.spritesheet_rows) {
                                                                                                        ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:86:56: error: no member named 'map_layer' in 'RPG::SavePicture'
                    int priority = Drawable::GetPriorityForMapLayer(data.map_layer);
                                                                    ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:134:7: error: no member named 'frames' in 'RPG::SavePicture'
            data.frames = 0;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:135:7: error: no member named 'spritesheet_rows' in 'RPG::SavePicture'
            data.spritesheet_rows = params.spritesheet_rows;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:136:7: error: no member named 'spritesheet_cols' in 'RPG::SavePicture'
            data.spritesheet_cols = params.spritesheet_cols;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:137:7: error: no member named 'spritesheet_play_once' in 'RPG::SavePicture'
            data.spritesheet_play_once = !params.spritesheet_loop;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:138:7: error: no member named 'spritesheet_frame' in 'RPG::SavePicture'
            data.spritesheet_frame = params.spritesheet_frame;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:139:7: error: no member named 'spritesheet_speed' in 'RPG::SavePicture'
            data.spritesheet_speed = params.spritesheet_speed;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:140:7: error: no member named 'map_layer' in 'RPG::SavePicture'
            data.map_layer = params.map_layer;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:141:7: error: no member named 'battle_layer' in 'RPG::SavePicture'
            data.battle_layer = params.battle_layer;
            ~~~~ ^
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/game_picture.cpp:142:7: error: no member named 'flags' in 'RPG::SavePicture'
            data.flags.erase_on_map_change = (params.flags & 1) == 1;
            ~~~~ ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    ninja: build stopped: subcommand failed.

**Comment by Ghabry** [comment]
Liblcf must be updated to 0.5.3.

**Comment by Ghabry** [comment]
Duplicate of #1292

**Comment by Ghabry** [comment]
looks solved: https://twitter.com/OpenBSD_ports/status/926622025254236160
