### ISSUE TITLE
Error at compiling latest branch 

### ISSUE THREAD

**Issue by Lang-Kasempo** [EasyRPG/Player#2384]
So, this a compilation error, not a game one. While trying to build, cmake gives this error:

> In file included from /home/lang/Player/src/algo.cpp:19:0:
/home/lang/Player/src/game_actor.h: In member function ‘void Game_Actor::SetName(const string&)’:
/home/lang/Player/src/game_actor.h:908:26: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
   : lcf::rpg::SaveActor::kEmptyName;
                                    ^~~~~~~~~~
/home/lang/Player/src/game_actor.h: In member function ‘virtual StringView Game_Actor::GetName() const’:
/home/lang/Player/src/game_actor.h:912:43: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
  return data.name != lcf::rpg::SaveActor::kEmptyName
                                           ^~~~~~~~~~
/home/lang/Player/src/game_actor.h: In member function ‘void Game_Actor::SetTitle(const string&)’:
/home/lang/Player/src/game_actor.h:920:26: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
   : lcf::rpg::SaveActor::kEmptyName;
                          ^~~~~~~~~~
/home/lang/Player/src/game_actor.h: In member function ‘StringView Game_Actor::GetTitle() const’:
/home/lang/Player/src/game_actor.h:924:44: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
  return data.title != lcf::rpg::SaveActor::kEmptyName
                                                               ^~~~~~~~~~
In file included from /home/lang/Player/src/attribute.cpp:24:0:
/home/lang/Player/src/game_actor.h: In member function ‘void Game_Actor::SetName(const string&)’:
/home/lang/Player/src/game_actor.h:908:26: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
   : lcf::rpg::SaveActor::kEmptyName;
                                    ^~~~~~~~~~
/home/lang/Player/src/game_actor.h: In member function ‘virtual StringView Game_Actor::GetName() const’:
/home/lang/Player/src/game_actor.h:912:43: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
  return data.name != lcf::rpg::SaveActor::kEmptyName
                                           ^~~~~~~~~~
/home/lang/Player/src/game_actor.h: In member function ‘void Game_Actor::SetTitle(const string&)’:
/home/lang/Player/src/game_actor.h:920:26: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
   : lcf::rpg::SaveActor::kEmptyName;
                                    ^~~~~~~~~~
/home/lang/Player/src/game_actor.h: In member function ‘StringView Game_Actor::GetTitle() const’:
/home/lang/Player/src/game_actor.h:924:44: error: ‘kEmptyName’ is not a member of ‘lcf::rpg::SaveActor’
  return data.title != lcf::rpg::SaveActor::kEmptyName 
                                                              ^~~~~~~~~~

> 

You know if I can fix this? Thanks

**Comment by Ghabry** [comment]
Hello. When building master you must also use the master of liblcf.
Or use the 0-6-2-stable branch. This builds with liblcf 0.6.2
